# Generated by Django 3.1.5 on 2022-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='erkhgbe', upload_to=''),
            preserve_default=False,
        ),
    ]
