# Generated by Django 3.1.5 on 2022-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_head',
        ),
        migrations.AddField(
            model_name='medicalworker',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
