version: "3.7"
services:
  db:
    image: "postgres"
    restart: "always"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    networks:
      - "djangonetwork"
    ports:
      - "5455:5432"
  web:
    build: "."
    image: "medapp:latest"
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - ".:/usr/src/app"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
    command: bash -c "python3 manage.py runserver [::]:8000"
    depends_on:
      - "db"
    networks:
      - "djangonetwork"

  redis:
   image: 'bitnami/redis:latest'
   ports:
     - '6379:6379'
   environment:
     - ALLOW_EMPTY_PASSWORD=yes
   networks:
     - "djangonetwork"

  celery:
   image: "medapp:latest"
   restart: "always"
   networks:
     - "djangonetwork"
   volumes:
     - ".:/usr/src/app"
   environment:
       - "DB_HOST=db"
       - "DB_NAME=postgres"
       - "DB_USER=postgres"
       - "DB_PASSWORD=postgres"
   command: bash -c "celery -A medapp worker -l INFO"
   depends_on:
     - "redis"

networks:
  djangonetwork:
    driver: bridge

